# Generated by Django 5.1.4 on 2025-01-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_api', '0002_locations_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
